[package]
name = "bachan"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
axum = "0.8.8"
censor = "0.3.0"
dotenv = "0.15.0"
lazy_static = "1.5.0"
regex = "1.12.3"
sanitize_html = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = [
     "chrono",
     "macros",
     "postgres",
     "runtime-tokio-rustls",
     "uuid",
] }
tera = "1.20.1"
tokio = { version = "1.49.0", features = ["full"] }
tower = "0.5.3"
tower-http = { version = "0.6.8", features = ["fs", "timeout"] }
uuid = { version = "1.23.0", features = ["serde"] }
