[package]
name = "bachan"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
axum = "0.8.8"
base64 = "0.22.1"
dotenv = "0.15.0"
lazy_static = "1.5.0"
maxminddb = "0.27.3"
real = { version = "0.1.4", features = ["axum"] }
regex = "1.12.3"
sanitize_html = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
siphasher = "1.0.2"
sqlx = { version = "0.8.6", features = [
     "chrono",
     "macros",
     "postgres",
     "runtime-tokio-rustls",
     "uuid",
] }
tera = { version = "1.20.1", features = ["builtins"] }
tokio = { version = "1.49.0", features = ["full"] }
tower = "0.5.3"
tower-http = { version = "0.6.8", features = [
	   "compression-gzip",
	   "fs",
	   "timeout",
] }
uuid = { version = "1.23.0", features = ["serde"] }
