services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://bachan:bachan1234@postgres/bachan
      - RUST_LOG=info
    env_file: ".env"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./static
        target: /app/static
        read_only: true

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bachan
      POSTGRES_PASSWORD: bachan1234
      POSTGRES_DB: bachan
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bachan"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: