ALTER TABLE thread ALTER COLUMN uid TYPE BIGINT;
ALTER TABLE reply ALTER COLUMN uid TYPE BIGINT;
ALTER TABLE PendingPost ALTER COLUMN uid TYPE BIGINT;
ALTER TABLE suspended ALTER COLUMN uid TYPE BIGINT;
